### ISSUE TITLE
408 request timeout

### ISSUE THREAD

**Issue by gghill** [bio-oracle/biooracler#14]
Hello,
After months of functionality this afternoon I began receiving `408 request timeout` errors with every call of `download_layers()`. Is there an issue with the ERDDAP server? My colleagues have had the same experience so I believe this is not an isolated incident. Please advise as to whether this is an error on my side or the package/server side.

Thanks for all your work on this super useful package,
Griffin

**Comment by yuliaUU** [comment]
i have the same issue now

**Comment by bart-v** [comment]
There was a server problem at our side.
This has now been fixed
